name: Deploy 

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 

    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v3
    
    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Step 4 - Build and deploy
      run: mvn --batch-mode deploy
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
