name: Deploy 

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 

    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v2
    
    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Step 4 - Build and deploy
      run: |
        mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml --batch-mode deploy
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USERNAME: ${{ secrets.USERNAME }}
        TOKEN: ${{ secrets.TOKEN }}
